version: '3'
services:  
  # PostgreSQL database
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: "redis:alpine"
    hostname: redis

  # Django web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: bash run_web.sh
    volumes:
      - .:/app  # mount current directory inside container
    ports:
      - "8000:8000"
    # set up links so that web knows about db, rabbit and redis
    links:
      - db
      - redis
    depends_on:
      - db

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash run_celery.sh
    volumes:
      - .:/app
    links:
      - db
      - redis
